### ISSUE TITLE
Build.PL incomplete

### ISSUE THREAD

**Issue by andk** [Csson/p5-Dist-Zilla-MintingProfile-Iller-CSSON#1]
http://www.cpantesters.org/cpan/report/64341076

This sample fail report comes due missing Moose. There are others for others, basically all of
these:

http://search.cpan.org/grep?release=Dist-Zilla-MintingProfile-Iller-CSSON-0.0100;string=Dist::Zilla::Role::MintingProfile|Moose|Path::Class|namespace::autoclean;n=1;C=0

Alternative view:

http://analysis.cpantesters.org/reports_by_field?SUBMIT_xxx=Submit&distv=Dist-Zilla-MintingProfile-Iller-CSSON-0.0100&field=qr%3A%28Can%27t+locate+\S%2Bpm%29&field=meta%3Aoutput_from&field=meta%3Awriter&field=qr%3A%28Can%27t+locate+\S%2Bpm%29

A big part of the fails comes from users of the Build.PL and indeed the Build.PL does not specify the prerequisites:

https://metacpan.org/source/CSSON/Dist-Zilla-MintingProfile-Iller-CSSON-0.0100/Build.PL

There seem to be other issues with other tools, but the broken Build.PL was just one thing easy to spot.

HTH&&Thanks,

**Comment by Csson** [comment]
Hi!

It shouldn't _have_ a Build.PL..

**Comment by Csson** [comment]
I've just released 0.0101 without Build.PL.

Thanks for reporting this.
